### ISSUE TITLE
Потрібно обраховувати роки які більше 1900 і менше 100000 а не навпаки

### ISSUE THREAD

**Issue by Muxamedin** [HennadiiPG/python_b#1]
https://github.com/HennadiiPG/python_b/blob/ee6bd2a4f1d1db244f19937b87124a1f0d82466a/lesson_4/lesson_4_part_4.2.py#L4

**Comment by HennadiiPG** [comment]
![image](https://user-images.githubusercontent.com/109980053/181919820-f95bf2f0-1842-4baa-bcb3-739ea772531b.png)
Умови виконано згідно з домашім завданням.  Якщо рік не відповідає вимогам - провести перевірку на високостний\невисокостний і повідомити в термінал. Вважаю зауваження не коректне.

**Comment by Muxamedin** [comment]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/4419752/181924887-f86fc667-beaa-4312-bf93-74d0600aa8fe.png">

Так - я бачу помилку в завданні 
Вибачте

Помилка:  "Якщо рік не відповідає вимогам"
Повинно бути :  "Якщо рік відповідає вимогам"

**Comment by HennadiiPG** [comment]
Виконав згідно завдання, перевірте будь ласка. Хочу розуміти на скільки вірно.  [lesson_4_part_4.2_correction.py](https://github.com/HennadiiPG/python_b/blob/main/lesson_4/lesson_4_part_4.2_correction.py)
