### ISSUE TITLE
Помилка в пошуку унікального значення

### ISSUE THREAD

**Issue by Muxamedin** [HennadiiPG/python_b#2]
https://github.com/HennadiiPG/python_b/blob/4d448bbf40f4f7ddbfbb94b47990939adc8e0784/lesson_7/lesson_7_part_3.py#L8

<img width="991" alt="image" src="https://user-images.githubusercontent.com/4419752/183964567-e65595ad-6b86-43da-9bab-23b2a811cb1c.png">
[1, 2, 3]  [3, 4, 5  ]
унікальних буде. 4 а не 5 - тому що 3 вже не унікальна і вона зустрічається 2 рази

**Comment by HennadiiPG** [comment]
Для того чтоб посчитать количество уникальных чисел одновременно в первом и втором списке мне ничего не мешает в первый список добавить второй и уже там считать количество уникальных. В сети я нашел что (класс set) - это контейнер, который содержит уникальные не повторяющиеся элементы в случайном порядке. Так тут возникает вопрос почему же если писать set(lst) считается и повторяющееся число? На основе этого была написана моя программа только без использования set(lst). 
![image](https://user-images.githubusercontent.com/109980053/184091954-fa9553d5-71e1-4e5b-bb25-930ba32d0c96.png)

**Comment by Muxamedin** [comment]
Я бачу багато прикладів такого рішення яке ви теж застосували 

Але якщо розглянути значення слова унікальний:
https://ru.wiktionary.org/wiki/%D1%83%D0%BD%D0%B8%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9

Я б назвав би щось унікальним якщо його аналогів немає в якомусь середовищі (у світі, в країні, в системі освіти, у місті, у списку з даними.....). Або воно не повторюється - неповторне.
Тип даних set  дійсно містить в собі лише унікальні занчення - що означає що кожне значення в set гарантовано буде лише одне і лише одне! 
Коли ви виконаєте перетворення списку до set то в ньому будуть унікальні значення. 

Але в цьому випадку ви не вирішуєте проблему унікальності елементів у списку - тому що ті числа які повторювались то вони не унікальні для цього списку/списків.

З огляду на set  я б розглядав метод symmetric_difference() для 2х наборів значень але знову ж хочу наголосити що це робота з наборими а не зі списками.

Але якщо вам дуже кортить не погоджуватися з тим що я написав - а саме опиратися на статю з прикладами в інтернеті (Хоча є і інші приклади) з могу боку нема проблем виправити вашу оцінку - лише скажіть. І тоді кожен заишитья при своїх розуміннях ситуаціі 
В будьякому випадку ви будете задоволені результатом - виправите ви так як  рекокомндую чи залишите так як у вас є.

**Comment by HennadiiPG** [comment]
Спасибо большое за развернутый ответ, я всего лишь хотел понять в чем разница и где именно свернул не туда. Теперь всё понятно. Оценка меня мало интересует, я пришел за знаниями.
